config/routes.rb
Rails.application.routes.draw do

  root 'static#home'

  get 'static/home'

  get 'static/about'

  resources :widgets

end

app/models/widget.rb
class Widget < ActiveRecord::Base
  validates :name, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end

end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  before_action :set_widget, only: [:show, :edit, :update, :destroy]

  # GET /widgets
  # GET /widgets.json
  def index
    @widgets = Widget.all
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    if @widget.nil?
      flash[:error] = "Item id was not valid"
      redirect_to widgets_path
    end #if
  end

  # GET /widgets/new
  def new
    @widget = Widget.new
  end

  # GET /widgets/1/edit
  def edit

#TODO: Refactor this down (appears in `def show` as well)
    if @widget.nil?
      flash[:error] = "Item id was not valid"
      redirect_to widgets_path
    end #if
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(widget_params)

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created' }
        format.json { render :show, status: :created, location: @widget }
      else
        flash[:error] = "Could not create Widget"
        format.html { render :new }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /widgets/1
  # PATCH/PUT /widgets/1.json
  def update
    respond_to do |format|
      if @widget.update(widget_params)
        format.html { redirect_to @widget, notice: 'Widget was successfully updated' }
        format.json { render :show, status: :ok, location: @widget }
      else
        flash[:error] = "Could not update Widget"
        format.html { render :edit }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget.destroy
    respond_to do |format|
      format.html { redirect_to widgets_url, notice: 'Widget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_widget
      @widget = Widget.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def widget_params
      params.require(:widget).permit(:name, :description, :picture, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

# Partial credit for title and meta_description helpers to David Lesches at
# http://davidlesches.com/blog/elegant-titles-and-seo-meta-tags-in-rails
  def title(title = nil)
    if title.present?
      content_for :title, title
    else
      if APP_CONFIG['default_title'] == nil
        default = APP_CONFIG['brand_name']
      else
        default = APP_CONFIG['default_title']
      end #if
      content_for?(:title) ? content_for(:title) + ' | ' +  default : default
    end #if
  end #title


  def company(company = nil)
    if company.present?
      content_for :company, company
    else
      if APP_CONFIG['company_name'] == nil
        default = APP_CONFIG['brand_name']
      else
        default = APP_CONFIG['company_name']
      end #if
      content_for?(:company) ? content_for(:company) + ' | ' +  default : default
    end #if
  end #title

  def meta_description(desc = nil)
    if desc.present?
      content_for :meta_description, desc
    else
      content_for?(:meta_description) ? content_for(:meta_description) : APP_CONFIG['default_desc']
    end #if
  end #title

  def canonical(canonical = nil)
    if canonical.present?
      content_for :canonical, canonical
    else
      content_for?(:canonical) ? content_for(:canonical) : APP_CONFIG['default_canonical']
    end #if
  end #title

  def bkg_start(bkg_start = nil)
    if bkg_start.present?
      content_for :bkg_start, bkg_start
    else content_for?(:bkg_start) ? content_for(:bkg_start) : ""
    end
  end #bkg_start

end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/application.html.haml
!!!
-# see helper methods in app/helpers/application_helper.rb
%html(lang="en")
  %head
    =render "shared/head"
  %body
    =render bkg_start #home_video.html.haml

    -# ------   Navigation Menus    ---- #
    =render "shared/main_nav"
    -#.off-canvas-wrap{ :'data-offcanvas' => true }
      -#=render "shared/off_canvas_nav"
      -# ----    Main Content       ---- #
    %section.main-section.inner-wrap
      =yield


    -# ------    Footer items       ---- #
    =render "shared/footer"

app/views/shared/_footer.html.haml
.row
  %footer
    .company-info{ itemscope: true, itemtype: "http://schema.org/Organization" }
      .location-info
        %span.company{ itemprop: "name"}
          = company
        %br
        %span.street{ itemprop: "streetAddress"}
          = APP_CONFIG['contact_address']
        %span.suite
          = APP_CONFIG['contact_suite']
        %br
        %span.city{ itemprop: "addressLocality"}
          = APP_CONFIG['contact_city']
        %span.state{ itemprop: "addressRegion"}
          = APP_CONFIG['contact_state']
        %span.postal
          = APP_CONFIG['contact_postal']
      .phone-info{ itemprop: "telephone"}
        = APP_CONFIG['contact_phone']
      .email-info{ itemprop: "email"}
        =link_to APP_CONFIG['contact_email_sales'], "mailto:#{APP_CONFIG['contact_email_sales']} "
    .webmaster
      =link_to APP_CONFIG['contact_email_web'], "mailto:#{APP_CONFIG['contact_email_web']} "
    .publication
      Published:
      %time{ pubdate: true, datetime: "2014-10-14" }
        10/14/2014
    .inh_kn_copy
      = raw APP_CONFIG['inh_kn_copy']

app/views/shared/_head.html.haml
%meta{ charset: 'utf-8' }
%meta{ name: 'viewport', content: 'width=device-width, initial-scale=1.0' }

%link{ rel: 'stylesheet', type: 'text/css', href: '//fonts.googleapis.com/css?family=Libre+Baskerville:400,700|Open+Sans:400italic,700italic,400,600,700,300' }

%link{ rel: 'canonical', href: canonical }
%link{ rel: 'author', href: '//humans.txt'}
%title
  = title
%meta{ content: meta_description, name: 'description' }
= stylesheet_link_tag    "application"
-# = javascript_include_tag "vendor/modernizr"
= csrf_meta_tags

app/views/shared/_home_video.html.haml
.video-bkg-container
  =video_tag ['3724946.webm', '3724946.ogg', '3724946.mp4', 'workingcomp800x530.jpg'], autoplay: true, loop: true, muted: true, poster: 'workingcomp800x530.jpg', id: 'top-video', alt: 'Video background for Inherent Knowledge web design in Jacksonville, FL- business is busy as a bee.'
.video-cover

app/views/shared/_main_nav.html.haml
-# On-canvas- larger screens
%section.main-nav
  %nav{ role: "navigation", :'aria-hidden' => true }
    %ul.pull-left
      =render "shared/menu_items"
    .pull-right
      %ul
        =link_to root_path do
          %li
            %label 555.555.5555
        =link_to root_path do
          %li
            %label example@email.com

app/views/shared/_masthead.html.haml
.row
  %header.masthead.medium-12.columns.show-for-medium-up
    %h2 Inherent Knowledge- Intelligent Business Web Design

app/views/shared/_menu_items.html.haml
-# ----    Menu Items    ---- #
=link_to root_path do
  .container
    %li
      %i.icon-beehive
      %label Home
=link_to root_path do
  .container
    %li
      %i.icon-waiting-bee-1
      %label Get a Quote
=link_to root_path do
  .container
    %li
      %i.icon-bee-with-jar
      %label Pricing
=link_to root_path do
  .container
    %li
      %i.icon-beekeeper-waving
      %label Blog
=link_to root_path do
  .container
    %li
      %i.icon-flying-bee
      %label Services
=link_to root_path do
  .container
    %li
      %i.icon-bee-over-honeycomb
      %label Portfolio

app/views/shared/_off_canvas_nav.html.haml
-# Off-canvas
.fixed.off-canvas-fixed
  %nav.tab-bar.hide-for-medium-up{ role: 'navigation' }
    .left-small
      =link_to('#', class: "left-off-canvas-toggle menu-icon", id: "expose_mobile_nav", role: 'button', :'aria-expanded' => false, :'aria-controls' => 'idOfMenu') do
        %span
    .right.tab-bar-section
      %h2.title
        Inherent Knowledge
  %nav.left-off-canvas-menu.main_nav
    %ul.off-canvas-list
      %li
        =link_to '#', id: 'off-canvas-title' do
          %label Navigation
      =render "shared/menu_items"

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.number_field :picture %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.erb
<h1>Listing widgets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @widgets.each do |widget| %>
      <tr>
        <td><%= widget.name %></td>
        <td><%= widget.description %></td>
        <td><%= widget.picture %></td>
        <td><%= widget.price %></td>
        <td><%= link_to 'Show', widget %></td>
        <td><%= link_to 'Edit', edit_widget_path(widget) %></td>
        <td><%= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Widget', new_widget_path %>

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @widget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @widget.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @widget.picture %>
</p>

<p>
  <strong>Price:</strong>
  <%= @widget.price %>
</p>

<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>